import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-[auto,1fr] h-screen">
          <SideNav />
          <div className="p-4">{children}</div>
        </div>
      </body>
    </html>
  );
}

function SideNav() {
  return (
    <aside className="overflow-hidden p-4 w-64 h-full bg-gray-400">
      <nav className="flex flex-col flex-wrap gap-4 items-stretch text-center">
        <Link
          className="mb-2 font-mono text-lg rounded hover:bg-blue-200"
          href="/"
        >
          EquipmentStore
        </Link>
        <Link className="text-lg rounded hover:bg-blue-200" href="locations">
          Locations
        </Link>
        <Link className="text-lg rounded hover:bg-blue-200" href="settings">
          Settings
        </Link>
      </nav>
    </aside>
  );
}
